# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.IntegerField(default=0)),
                ('owner', models.CharField(default='undefined', max_length=30)),
                ('name', models.CharField(max_length=200, null=True)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=5000, null=True)),
                ('author', models.CharField(default='undefined', max_length=50)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_timestamp', models.DateTimeField(null=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
